### ISSUE TITLE
Unhandled exception in end_request subscriber

### ISSUE THREAD

**Issue by displacedaussie** [collective/collective.linkcheck#4]
There's a strange bug in one of my Plone sites that I haven't been able to debug or understand fully, but the unhandled exception is resulting in some significant problems.

With collective.linkcheck installed, viewing one of my pages results in the following stack trace:

```
2015-02-08T09:21:46 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/var/buildout/buildout-cache/plone/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/Publish.py", line 443, in publish_module
    environ, debug, request, response)
  File "/var/buildout/buildout-cache/plone/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/Publish.py", line 264, in publish_module_standard
    if request is not None: request.close()
  File "/var/buildout/buildout-cache/plone/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/var/buildout/buildout-cache/plone/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/var/buildout/buildout-cache/plone/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/var/buildout/buildout-cache/plone/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/buildout/buildout-cache/plone/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/buildout/buildout-cache/plone/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/buildout/buildout-cache/plone/eggs/collective.linkcheck-1.2-py2.7.egg/collective/linkcheck/events.py", line 124, in end_request
    tool.register(hrefs, referer, yesterday)
  File "/var/buildout/buildout-cache/plone/eggs/collective.linkcheck-1.2-py2.7.egg/collective/linkcheck/tool.py", line 116, in register
    index = self.enqueue(href)
  File "/var/buildout/buildout-cache/plone/eggs/collective.linkcheck-1.2-py2.7.egg/collective/linkcheck/tool.py", line 76, in enqueue
    entry = None, entry[1], entry[2]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

But I haven't been able to understand why ```entry``` is None at this point in the enqueue method.

The significant issue here is that the exception in the end_request subscriber is triggering a Zope bug (raised and subsequently fixed here: https://github.com/zopefoundation/Zope/issues/16 ).

The linkcheck tool should possibly include some exception handling for when items on the queue are invalid so that exceptions aren't raised during this event subscriber.

**Comment by gforcada** [comment]
@displacedaussie have you tried to add a pdb on c.linkcheck? that's the way you get to know at least why ``entry`` is None.
